name: warung_bioskop
description: "Warung Bioskop is provide movie list and ticketing simulation"

version: 1.32.1+1

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.6.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3

flutter:

  uses-material-design: true
