name: warung_bioskop
description: "Warung Bioskop is provide movie list and ticketing simulation"

version: 1.32.2+2

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.0
  crypto: ^3.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  encrypt: ^5.0.0
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_remote_config: ^5.4.1
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.6.3
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.1
  json_annotation: ^4.9.0
  path: ^1.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.5.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.1
  riverpod_lint: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/
