name: warung_bioskop
description: "Warung Bioskop is provide movie list and ticketing simulation"

version: 1.32.1+1

environment:
  sdk: ^3.5.3

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.7.1

flutter:

  uses-material-design: true